// app/src/components/ui/card.tsx
import * as React from 'react'

import { cn } from '@/lib/utils'

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ className, ...props }, ref) => (
    <div ref={ref} className={cn('rounded-xl bg-zinc-900 text-card-foreground shadow-sm', className)} {...props} />
))
Card.displayName = 'Card'

const CardContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
    ({ className, ...props }, ref) => <div ref={ref} className={cn('p-6 pt-0', className)} {...props} />,
)
CardContent.displayName = 'CardContent'

const CardFooter = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
    ({ className, ...props }, ref) => (
        <div ref={ref} className={cn('flex items-center justify-center p-6 pt-0', className)} {...props} />
    ),
)
CardFooter.displayName = 'CardFooter'

export { Card, CardFooter, CardContent }

// app/src/components/ui/card.svelte
<script lang="ts">
</script>

<div class="text-card-foreground rounded-xl border border-zinc-800 bg-zinc-900 shadow-sm">
    <div class="flex items-center space-x-4 px-8 pt-8">
        <slot name="content" />
    </div>
    <div class="flex items-center justify-center p-6">
        <slot name="footer" />
    </div>
</div>
